version: "2"
issues:
  new: true
  new-from-rev: origin/main
linters:
  disable-all: true
  enable:
  - errcheck
  - gocritic
  - goheader
  - govet
  - ineffassign
  - lll
  - misspell
  - predeclared
  - revive
  - staticcheck
  - thelper
  - tparallel
  - unused
formatters:
  enable:
  - gofumpt
  - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes: github.com/scylladb-actions/get-version
run:
  allow-parallel-runners: true
  timeout: 2m
  modules-download-mode: readonly
  tests: true
  go: '1.25'
linters-settings:
  govet:
    enable-all: true
    disable:
    - shadow
    - fieldalignment
